# Nome: Gustavo Mendes Maciel
# NUSP: 9298062
#
# Nome: Marcelo Baiano Pastorino Trylesinski
# NUSP: 9297996
#
# MAC0219 - MiniEP2
#

CC=gcc
CFLAGS=-std=c99 -pthread

frogs: frogs.c
	$(CC) -o frogs frogs.c $(CFLAGS)

clean:
	rm frogs
